// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gamestone/app"
	"gamestone/config"
	"gamestone/container"
	"gamestone/handlers"
	"gamestone/providers"
	"gamestone/repositories"
	"gamestone/services"
	"gamestone/tasks"
)

// Injectors from wire.go:

// Initialize App
func InitializeApp() (*container.AppContainer, error) {
	appConfig := config.LoadAppConfig()
	databaseConfig := config.LoadDatabaseConfig()
	db, err := providers.NewDBConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	gameRepository := repositories.NewGameRepository(db)
	gameService := services.NewGameService(gameRepository)
	validate := providers.NewValidator()
	gameHandler := handlers.NewGameHandler(gameService, validate)
	appContainer, err := app.NewFiberApp(appConfig, gameHandler)
	if err != nil {
		return nil, err
	}
	return appContainer, nil
}

// Initialize Worker
func InitializeWorker() (*container.WorkerContainer, error) {
	appConfig := config.LoadAppConfig()
	redisConfig := config.LoadRedisConfig()
	databaseConfig := config.LoadDatabaseConfig()
	db, err := providers.NewDBConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	gameRepository := repositories.NewGameRepository(db)
	gameService := services.NewGameService(gameRepository)
	gameTask := tasks.NewGameTask(gameService)
	workerContainer, err := app.NewAsynqWorker(appConfig, redisConfig, gameTask)
	if err != nil {
		return nil, err
	}
	return workerContainer, nil
}
