// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gamestone/app"
	"gamestone/config"
	"gamestone/container"
	"gamestone/database"
	"gamestone/handlers"
	"gamestone/repositories"
	"gamestone/services"
	"gamestone/validator"
)

// Injectors from wire.go:

// Initialize App
func InitializeApp() (*container.AppContainer, error) {
	appConfig := config.LoadAppConfig()
	databaseConfig := config.LoadDatabaseConfig()
	db, err := database.ConnectDB(databaseConfig)
	if err != nil {
		return nil, err
	}
	gameRepository := repositories.NewGameRepository(db)
	gameService := services.NewGameService(gameRepository)
	validate := validator.ProvideValidator()
	gameHandler := handlers.NewGameHandler(gameService, validate)
	appContainer, err := app.NewFiberApp(appConfig, gameHandler)
	if err != nil {
		return nil, err
	}
	return appContainer, nil
}
